// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("backend.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnswerCorrect")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnswerFour")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnswerOne")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnswerThree")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnswerTwo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TemaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnswerCorrect = "9",
                            AnswerFour = "10",
                            AnswerOne = "7",
                            AnswerThree = "9",
                            AnswerTwo = "8",
                            TemaId = 1,
                            Title = "Quanto é 5 + 4 = ? "
                        },
                        new
                        {
                            Id = 2,
                            AnswerCorrect = "14",
                            AnswerFour = "14",
                            AnswerOne = "7",
                            AnswerThree = "15",
                            AnswerTwo = "11",
                            TemaId = 1,
                            Title = "Quanto é 10 + 4 = ? "
                        },
                        new
                        {
                            Id = 3,
                            AnswerCorrect = "6",
                            AnswerFour = "10",
                            AnswerOne = "6",
                            AnswerThree = "4",
                            AnswerTwo = "8",
                            TemaId = 1,
                            Title = "Quanto é 3 + 3 = ? "
                        },
                        new
                        {
                            Id = 4,
                            AnswerCorrect = "11",
                            AnswerFour = "18",
                            AnswerOne = "10",
                            AnswerThree = "29",
                            AnswerTwo = "11",
                            TemaId = 1,
                            Title = "Quanto é 2 + 9 = ? "
                        },
                        new
                        {
                            Id = 5,
                            AnswerCorrect = "2",
                            AnswerFour = "11",
                            AnswerOne = "3",
                            AnswerThree = "2",
                            AnswerTwo = "4",
                            TemaId = 1,
                            Title = "Quanto é 1 + 1 = ? "
                        },
                        new
                        {
                            Id = 6,
                            AnswerCorrect = "1",
                            AnswerFour = "6",
                            AnswerOne = "7",
                            AnswerThree = "9",
                            AnswerTwo = "1",
                            TemaId = 4,
                            Title = "Quanto é 5 - 4 = ? "
                        },
                        new
                        {
                            Id = 7,
                            AnswerCorrect = "2",
                            AnswerFour = "1",
                            AnswerOne = "12",
                            AnswerThree = "2",
                            AnswerTwo = "3",
                            TemaId = 4,
                            Title = "Quanto é 7 - 5 = ? "
                        },
                        new
                        {
                            Id = 8,
                            AnswerCorrect = "0",
                            AnswerFour = "8",
                            AnswerOne = "0",
                            AnswerThree = "5",
                            AnswerTwo = "3",
                            TemaId = 4,
                            Title = "Quanto é 10 - 10 = ? "
                        },
                        new
                        {
                            Id = 9,
                            AnswerCorrect = "4",
                            AnswerFour = "12",
                            AnswerOne = "2",
                            AnswerThree = "4",
                            AnswerTwo = "6",
                            TemaId = 4,
                            Title = "Quanto é 8 - 4 = ? "
                        },
                        new
                        {
                            Id = 10,
                            AnswerCorrect = "8",
                            AnswerFour = "10",
                            AnswerOne = "7",
                            AnswerThree = "9",
                            AnswerTwo = "8",
                            TemaId = 4,
                            Title = "Quanto é 15 - 7 = ? "
                        });
                });

            modelBuilder.Entity("backend.Models.Tema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Temas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Adição"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Subtração"
                        });
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailAddress = "guto.admin@email.com",
                            Password = "guto12345",
                            Role = "Administrator",
                            UserName = "guto_admin"
                        },
                        new
                        {
                            Id = 2,
                            EmailAddress = "tah@email.com",
                            Password = "tah12345",
                            Role = "Standard",
                            UserName = "tah_standard"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
